# Generated by Django 2.2.28 on 2022-06-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_key', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('length', models.FloatField(default=0)),
                ('lang', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('is_exported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('length', models.FloatField(default=0)),
                ('lang', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.AudioFile')),
            ],
        ),
    ]
