# Generated by Django 2.2.28 on 2022-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='snr',
            field=models.FloatField(default=0),
        ),
    ]
