# Generated by Django 2.2.28 on 2022-06-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_utterance_snr'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelink',
            name='collection_key',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
