# Generated by Django 2.2.28 on 2022-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_youtubelink_collection_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelink',
            name='lang',
            field=models.CharField(default='-', max_length=2),
        ),
    ]
