# Generated by Django 2.2.28 on 2022-06-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_youtubelink_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('length', models.FloatField(default=0)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.AudioFile')),
            ],
        ),
    ]
