# Generated by Django 2.2.28 on 2022-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_audiochunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('collection_key', models.CharField(default='-', max_length=50)),
                ('is_exported', models.BooleanField(default=False)),
                ('lang', models.CharField(default='-', max_length=2)),
            ],
        ),
    ]
