# Generated by Django 2.2.28 on 2022-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_audiolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_key', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('length', models.FloatField(default=0)),
                ('lang', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
