# Generated by Django 2.2.28 on 2022-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='length',
        ),
        migrations.AddField(
            model_name='videofile',
            name='is_exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='collection_key',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='lang',
            field=models.CharField(default='-', max_length=2),
        ),
    ]
