# Generated by Django 2.2.28 on 2022-07-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20220630_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_key', models.CharField(default='-', max_length=50)),
            ],
        ),
    ]
