# Generated by Django 4.1.3 on 2022-11-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_alter_audiochunk_id_alter_audiofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='label_lang',
            field=models.CharField(default='--', max_length=2),
        ),
        migrations.AddField(
            model_name='utterance',
            name='loudness',
            field=models.FloatField(default=0),
        ),
    ]
