# Generated by Django 4.1.3 on 2022-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_utterance_label_lang_utterance_loudness'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='audio_lang',
            field=models.CharField(default='--', max_length=2),
        ),
    ]
