# Generated by Django 4.1.3 on 2022-12-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_utterance_audio_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('collection_key', models.CharField(default='-', max_length=50)),
                ('is_exported', models.BooleanField(default=False)),
                ('lang', models.CharField(default='-', max_length=2)),
            ],
        ),
    ]
