# Generated by Django 4.1.3 on 2022-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0013_localfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='srmr_ratio',
            field=models.FloatField(default=0),
        ),
    ]
