# Generated by Django 4.1.3 on 2022-12-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0015_youtubechannellink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addr", models.CharField(max_length=500)),
            ],
        ),
    ]
