# Generated by Django 4.1.3 on 2022-12-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0016_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='filesize',
            field=models.FloatField(default=0),
        ),
    ]
