# Generated by Django 4.1.3 on 2023-01-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0017_utterance_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='audio_type',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
